#version 460
layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

struct Camera
{
    vec3 position; float _pad0;
    vec3 forward; float _pad1;
    vec3 right; float _pad2;
    vec3 up; float _pad3;
    vec3 Q; float _pad4;
    float sUMult; float sVMult;
    float _pad5;float _pad6;
};

struct SceneGlobals
{
    vec3 ambientLight;
    float _pad0;
};

layout( push_constant ) uniform constants
{
    float time;
} PushConstants;

layout(set = 1, binding = 0) uniform SceneBuffer
{
    SceneGlobals globals;
};

layout(set = 1, binding = 1) readonly buffer CameraBuffer
{
    Camera camera;
};

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(outputImage);

    if (pixel.x >= size.x || pixel.y >= size.y)
    return;

    Camera cam = camera;

    vec3 s = cam.Q + pixel.x * cam.sUMult * cam.right -pixel.y * cam.sVMult * cam.up;

    vec3 rd = normalize(s - cam.position); // Ray direction
    vec3 ro = cam.position; // Ray origin
    
    // Simple gradient background based on ray direction
    vec3 color = 0.5 * (rd + vec3(1.0, 1.0, 1.0));

    imageStore(outputImage, pixel, vec4(color, 1.0));
}